Ejercicio 1. Sea $\{ X_n \}_{n\geq 0}$ una Cadena de Markov con espacio de estados $\mathbb{E}=\{ 0,1,2,3 \}$ y matriz de probabilidades de transición: 

$\mathbb{P}= \begin{pmatrix}
1-p & p & 0 & 0\\
0 & 0 & 1-p & p\\
1-p & p & 0 & 0\\
0 & 1 & 0 & 0
\end{pmatrix}$

a) Encuentre (si existe) su distribución estacionaria.

b) Diseñe un algoritmo que simule la cadena.

c) Para tres valores distintos de $p$ (indicarlos) y números de pasos $M=100, 1000$, simule la cadena iniciando en $j$ y calcule $\frac{N_j^M}{M}$ ($N_j^M$ es el número de visitas al estado $j$ hasta el tiempo $M$) para $j=0,1,2$. Compare con la distribución estacionaria obtenida en a). 

SOLUCIONES.

a) Solución.

Ver ejercicio en la tarea escrita a mano. La distribución estacionaria obtenida es:

$\pi = (\frac{p^2-2p+1}{p^2+1}, \frac{p}{p^2+1}, \frac{p-p^2}{p^2+1}, \frac{p^2}{p^2+1})$

Para distintos valores de $p$ tendríamos:

$\pi  = (\frac{(0.75)^2-2(0.75)+1}{(0.75)^2+1}, \frac{(0.75)}{(0.75)^2+1}, \frac{(0.75)-(0.75)^2}{(0.75)^2+1}, \frac{(0.75)^2}{(0.75)^2+1}) = (0.04, 0.48, 0.12, 0.36)$

$\pi  = (\frac{(0.5)^2-2(0.5)+1}{(0.5)^2+1}, \frac{(0.5)}{(0.5)^2+1}, \frac{(0.5)-(0.5)^2}{(0.5)^2+1}, \frac{(0.5)^2}{(0.5)^2+1}) = (0.2, 0.4, 0.2, 0.2)$

$\pi  = (\frac{(0.25)^2-2(0.25)+1}{(0.25)^2+1}, \frac{(0.25)}{(0.25)^2+1}, \frac{(0.25)-(0.25)^2}{(0.25)^2+1}, \frac{(0.25)^2}{(0.25)^2+1}) = (0.52941176471,0.23529411765,0.17647058824,0.05882352941)$

PASOS DE LA SOLUCIÓN.

$\pi = \pi \mathbb{P}$  $\rightarrow$  $(\pi_0, \pi_1, \pi_2, \pi_3) = (\pi_0, \pi_1, \pi_2, \pi_3) \begin{pmatrix}
1-p & p & 0 & 0\\
0 & 0 & 1-p & p\\
1-p & p & 0 & 0\\
0 & 1 & 0 & 0
\end{pmatrix}$ = $\left(\begin{matrix}
-p \pi_0+\pi_0-p \pi_2+\pi_2, & p \pi_0+p \pi_2+\pi_3, & -p \pi_1+\pi_1, & p \pi_1
\end{matrix}\right)$

\begin{cases} 
      \pi_0 = & (1-p)\pi_0+(1-p)\pi_2 \\
      \pi_1 = & p\pi_0+p\pi_2+\pi_3 \\
      \pi_2 = & (1-p)\pi_1 \\
      \pi_3 = & p\pi_1 
\end{cases}

\begin{cases} 
      \pi_0 -\frac{(1-p)}{p}\pi_2 =  0 \\
      p\pi_0-\pi_1+p\pi_2+\pi_3 =  0 \\
      (1-p)\pi_1-\pi_2 =  0 \\
      p\pi_1-\pi_3 =  0
\end{cases}

Tomando en cuenta la condición $\pi_0+\pi_1+\pi_2+\pi_3=1$, resolveremos el siguiente sistema de ecuaciones: 

$\left(\begin{matrix}
1 & 0 & \frac{p-1}{p} & 0 & | 0 \\
p & -1 & p & 1 & | 0 \\
0 & -p+1 & -1 & 0 & | 0 \\
0 & p & 0 & -1 & | 0 \\
1 & 1 & 1 & 1 & | 1
\end{matrix}\right)$ $\rightarrow$ $\left(\begin{matrix}
1 & 0 & \frac{p-1}{p} & 0 & 0 \\
0 & -1 & 1 & 1 & 0 \\
0 & -p+1 & -1 & 0 & 0 \\
0 & p & 0 & -1 & 0 \\
1 & 1 & 1 & 1 & 1
\end{matrix}\right)$ $\rightarrow$ $\left(\begin{matrix}
1 & 0 & \frac{p-1}{p} & 0 & 0 \\
0 & -1 & 1 & 1 & 0 \\
0 & -p+1 & -1 & 0 & 0 \\
0 & p & 0 & -1 & 0 \\
0 & 1 & \frac{1}{p} & 1 & 1
\end{matrix}\right)$ $\rightarrow$ $\left(\begin{matrix}
1 & 0 & \frac{p-1}{p} & 0 & 0 \\
0 & -1 & 1 & 1 & 0 \\
0 & 0 & -p & -p+1 & 0 \\
0 & p & 0 & -1 & 0 \\
0 & 1 & \frac{1}{p} & 1 & 1
\end{matrix}\right)$ $\rightarrow$  $\left(\begin{matrix}
1 & 0 & \frac{p-1}{p} & 0 & 0 \\
0 & -1 & 1 & 1 & 0 \\
0 & 0 & -p & -p+1 & 0 \\
0 & 0 & p & p-1 & 0 \\
0 & 1 & \frac{1}{p} & 1 & 1
\end{matrix}\right)$

$\rightarrow$ $\left(\begin{matrix}
1 & 0 & \frac{p-1}{p} & 0 & 0 \\
0 & -1 & 1 & 1 & 0 \\
0 & 0 & -p & -p+1 & 0 \\
0 & 0 & p & p-1 & 0 \\
0 & 0 & \frac{p+1}{p} & 2 & 1
\end{matrix}\right)$  $\rightarrow$ $\left(\begin{matrix}
1 & 0 & \frac{p-1}{p} & 0 & 0 \\
0 & -1 & 1 & 1 & 0 \\
0 & 0 & -p & -p+1 & 0 \\
0 & 0 & 0 & 0 & 0 \\
0 & 0 & \frac{p+1}{p} & 2 & 1
\end{matrix}\right)$ $\rightarrow$ $\left(\begin{matrix}
1 & 0 & \frac{p-1}{p} & 0 & 0 \\
0 & -1 & 1 & 1 & 0 \\
0 & 0 & -p & -p+1 & 0 \\
0 & 0 & 0 & 0 & 0 \\
0 & 0 & 0 & \frac{p^2+1}{p^2} & 1
\end{matrix}\right)$ $\rightarrow$ $\left(\begin{matrix}
1 & 0 & \frac{p-1}{p} & 0 & 0 \\
0 & -1 & 1 & 1 & 0 \\
0 & 0 & -p & -p+1 & 0 \\
0 & 0 & 0 & 0 & 0 \\
0 & 0 & 0 & \frac{p^2+1}{p^2} & 1
\end{matrix}\right)$ $\rightarrow$ $\left(\begin{matrix}
1 & 0 & \frac{p-1}{p} & 0 & 0 \\
0 & -1 & 1 & 1 & 0 \\
0 & 0 & -p & -p+1 & 0 \\
0 & 0 & 0 & \frac{p^2+1}{p^2} & 1 \\
0 & 0 & 0 & 0 & 0
\end{matrix}\right)$

$\pi= \left(\begin{matrix}
\pi_0 \\
\pi_1 \\
\pi_2 \\
\pi_3
\end{matrix}\right)$ =  $\left(\begin{matrix}
\frac{p^2-2p+1}{p^2+1} \\
\frac{p}{p^2+1} \\
\frac{-p^2+p}{p^2+1} \\
\frac{p^2}{p^2+1}
\end{matrix}\right)$

*
*
*
*
*
*
*
*
*

1. b) Solución.

In [1]:
import numpy as np

In [2]:
E={0:"0", 1:"1", 2:"2",3:"3"} #Espacio de estados
E

{0: '0', 1: '1', 2: '2', 3: '3'}

In [3]:
p=0.75 #probabilidad p (cambiar para varios valores)
P=np.array([[1-p, p, 0, 0],[0,0,1-p,p],[1-p,p,0,0],[0,1,0,0]]) #Matriz de probabilidades de transición.
P

array([[0.25, 0.75, 0.  , 0.  ],
       [0.  , 0.  , 0.25, 0.75],
       [0.25, 0.75, 0.  , 0.  ],
       [0.  , 1.  , 0.  , 0.  ]])

In [4]:
#Cadena
M=100 #número de pasos
start_state=0 #Estado inicial
print(E[start_state], "--->", end=" ")
prev_state=start_state

while M-1:
    curr_state=np.random.choice([0,1,2,3], p=P[prev_state])
    print(E[curr_state], "--->", end=" ")
    prev_state=curr_state
    M-=1
print("stop")


0 ---> 1 ---> 3 ---> 1 ---> 3 ---> 1 ---> 3 ---> 1 ---> 3 ---> 1 ---> 2 ---> 1 ---> 3 ---> 1 ---> 3 ---> 1 ---> 2 ---> 1 ---> 3 ---> 1 ---> 3 ---> 1 ---> 3 ---> 1 ---> 3 ---> 1 ---> 2 ---> 1 ---> 3 ---> 1 ---> 3 ---> 1 ---> 3 ---> 1 ---> 3 ---> 1 ---> 2 ---> 1 ---> 3 ---> 1 ---> 3 ---> 1 ---> 2 ---> 1 ---> 3 ---> 1 ---> 3 ---> 1 ---> 3 ---> 1 ---> 2 ---> 0 ---> 1 ---> 3 ---> 1 ---> 2 ---> 1 ---> 3 ---> 1 ---> 3 ---> 1 ---> 2 ---> 0 ---> 1 ---> 3 ---> 1 ---> 3 ---> 1 ---> 3 ---> 1 ---> 3 ---> 1 ---> 2 ---> 0 ---> 1 ---> 3 ---> 1 ---> 3 ---> 1 ---> 2 ---> 0 ---> 0 ---> 1 ---> 3 ---> 1 ---> 2 ---> 1 ---> 3 ---> 1 ---> 3 ---> 1 ---> 3 ---> 1 ---> 3 ---> 1 ---> 3 ---> 1 ---> 3 ---> 1 ---> 2 ---> stop


1. c.i) Solución para $100$ pasos y distintos valores de $p\in \{0.75, 0.5, 0.25\}$.

In [5]:
#Distribución estacionaria
#Método: Monte Carlo
p=0.75 #probabilidad p (cambiar para varios valores)
P=np.array([[1-p, p, 0, 0],[0,0,1-p,p],[1-p,p,0,0],[0,1,0,0]]) #Matriz de probabilidades de transición.

M=100 #Número de pasos
start_state=0 #Estado inicial
pi=np.array([0,0,0,0]) #Variable que contendrá la distribución estacionaria
pi[start_state]=1
prev_state=start_state #variable del estado anterior

i=0
while i<M:
    curr_state=np.random.choice([0,1,2,3], p=P[prev_state])
    pi[curr_state]+=1
    prev_state=curr_state
    i+=1
print("Número de visitas de los estados = ", pi)
print("Probabilidad Estacionaria = ", pi/M) #Probabilidad estacionaria


Número de visitas de los estados =  [ 3 49 11 38]
Probabilidad Estacionaria =  [0.03 0.49 0.11 0.38]


In [6]:
#Distribución estacionaria
#Método: Repeated Matrix Multiplication
p=0.5 #probabilidad p (cambiar para varios valores)
P=np.array([[1-p, p, 0, 0],[0,0,1-p,p],[1-p,p,0,0],[0,1,0,0]]) #Matriz de probabilidades de transición.

M=100 #Número de pasos
P_n=P

i=0
while i<M:
    P_n=np.matmul(P_n,P)
    i+=1
    
print("P^n=  \n", P_n, "\n")
print("Probabilidad Estacionaria =", P_n[0])



P^n=  
 [[0.2 0.4 0.2 0.2]
 [0.2 0.4 0.2 0.2]
 [0.2 0.4 0.2 0.2]
 [0.2 0.4 0.2 0.2]] 

Probabilidad Estacionaria = [0.2 0.4 0.2 0.2]


In [7]:
#Distribución estacionaria
#Método: Finding Left Eigen Vectors
p=0.25 #probabilidad p (cambiar para varios valores)
P=np.array([[1-p, p, 0, 0],[0,0,1-p,p],[1-p,p,0,0],[0,1,0,0]]) #Matriz de probabilidades de transición.

import scipy.linalg
values, left=scipy.linalg.eig(P, right=False, left=True)

print("left eigen vectors = \n", left, "\n")
print("eigen values = \n", values)

pi=left[:,0]
pi_normalized=[(x/np.sum(pi)).real for x in pi]
print("Probabilidad Estacionaria =", pi_normalized)

left eigen vectors = 
 [[-8.70062840e-01 -3.98017671e-01  7.07106781e-01 -8.40370643e-01]
 [-3.86694596e-01 -5.40026066e-01  2.29023974e-16  2.06460630e-01]
 [-2.90020947e-01  7.03532802e-01 -7.07106781e-01  4.75432510e-01]
 [-9.66736489e-02  2.34510934e-01 -1.21180057e-17  1.58477503e-01]] 

eigen values = 
 [ 1.00000000e+00+0.j -5.75693909e-01+0.j -4.98539399e-17+0.j
  3.25693909e-01+0.j]
Probabilidad Estacionaria = [0.5294117647058817, 0.23529411764705918, 0.17647058823529443, 0.0588235294117648]


1. c.ii) Solución para $1000$ pasos y distintos valores de $p\in \{0.75, 0.5, 0.25\}$.

In [9]:
#Distribución estacionaria
#Método: Monte Carlo
p=0.75 #probabilidad p (cambiar para varios valores)
P=np.array([[1-p, p, 0, 0],[0,0,1-p,p],[1-p,p,0,0],[0,1,0,0]]) #Matriz de probabilidades de transición.

M=1000 #Número de pasos
start_state=0 #Estado inicial
pi=np.array([0,0,0,0]) #Variable que contendrá la distribución estacionaria
pi[start_state]=1
prev_state=start_state #variable del estado anterior

i=0
while i<M:
    curr_state=np.random.choice([0,1,2,3], p=P[prev_state])
    pi[curr_state]+=1
    prev_state=curr_state
    i+=1
print("Número de visitas de los estados = ", pi)
print("Probabilidad Estacionaria = ", pi/M) #Probabilidad estacionaria

Número de visitas de los estados =  [ 38 482 114 367]
Probabilidad Estacionaria =  [0.038 0.482 0.114 0.367]


In [10]:
#Distribución estacionaria
#Método: Repeated Matrix Multiplication
p=0.5 #probabilidad p (cambiar para varios valores)
P=np.array([[1-p, p, 0, 0],[0,0,1-p,p],[1-p,p,0,0],[0,1,0,0]]) #Matriz de probabilidades de transición.

M=1000 #Número de pasos
P_n=P

i=0
while i<M:
    P_n=np.matmul(P_n,P)
    i+=1
    
print("P^n=  \n", P_n, "\n")
print("Probabilidad Estacionaria =", P_n[0])

P^n=  
 [[0.2 0.4 0.2 0.2]
 [0.2 0.4 0.2 0.2]
 [0.2 0.4 0.2 0.2]
 [0.2 0.4 0.2 0.2]] 

Probabilidad Estacionaria = [0.2 0.4 0.2 0.2]


In [11]:
#Distribución estacionaria
#Método: Finding Left Eigen Vectors
p=0.25 #probabilidad p (cambiar para varios valores)
P=np.array([[1-p, p, 0, 0],[0,0,1-p,p],[1-p,p,0,0],[0,1,0,0]]) #Matriz de probabilidades de transición.

import scipy.linalg
values, left=scipy.linalg.eig(P, right=False, left=True)

print("left eigen vectors = \n", left, "\n")
print("eigen values = \n", values)

pi=left[:,0]
pi_normalized=[(x/np.sum(pi)).real for x in pi]
print("Probabilidad Estacionaria =", pi_normalized)

left eigen vectors = 
 [[-8.70062840e-01 -3.98017671e-01  7.07106781e-01 -8.40370643e-01]
 [-3.86694596e-01 -5.40026066e-01  2.29023974e-16  2.06460630e-01]
 [-2.90020947e-01  7.03532802e-01 -7.07106781e-01  4.75432510e-01]
 [-9.66736489e-02  2.34510934e-01 -1.21180057e-17  1.58477503e-01]] 

eigen values = 
 [ 1.00000000e+00+0.j -5.75693909e-01+0.j -4.98539399e-17+0.j
  3.25693909e-01+0.j]
Probabilidad Estacionaria = [0.5294117647058817, 0.23529411764705918, 0.17647058823529443, 0.0588235294117648]
